name: ci-go-lang-workflow
on:
  push:
    branches:
      - master
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20.5'
      - run: go run math.go