name: ci-go-lang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    strategy:
      matrix:
        go-version: ['1.19','1.20.5']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test
      - run: go run math.go